function getmedician (){
  const medicianNames = [
    "Cleanser",
    "Toner",
    "Moisturizer",
    "Sunscreen",
    "Serum",
    "Exfoliator",
    "Mask",
    "Eye cream",
    "Spot treatment",
    "Face oil",
    "Essence",
    "Sheet mask",
    "Face mist",
    "Ampoule",
    "Facial roller",
    "Night cream",
    "Face wash",

    // Haircare
    "Shampoo",
    "Conditioner",
    "Hair mask",
    "Hair oil",
    "Hair serum",
    "Leave-in conditioner",
    "Scalp treatment",
    "Hair spray",
    "Dry shampoo",
    "Hair gel",
    "Hair wax",
    "Hair mousse",
    "Hair tonic",
    "Hair gloss",
    "Heat protectant",
    "Texturizing spray",
    "Curl cream",

    // Makeup
    "Foundation",
    "Concealer",
    "Powder",
    "Blush",
    "Bronzer",
    "Highlighter",
    "Eyeshadow",
    "Eyeliner",
    "Mascara",
    "Eyebrow pencil",
    "Lipstick",
    "Lip gloss",
    "Lip liner",
    "Setting spray",
    "Primer",
    "Makeup remover",
    "BB cream",
    "CC cream"
  ];
  return medicianNames
}
export default getmedician